name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - mamba
  - pip
  - ipython
  - cookiecutter
  - flake8
  - black
  - isort
  - pandoc
  - jupyter
  - jupyterlab
  - jupytext
  - jupyterlab-system-monitor
  - jupyterlab-spellchecker
  - jupyterlab-git
